trusted_authority_sign_url = "http://localhost:5000/sign"
trusted_authority_vote_count_url = "http://localhost:5000/vote_count"
trusted_authority_public_key_url = "http://localhost:5000/public_key"
trusted_authority_verify_url = "http://localhost:5000/verify"
trusted_authority_vote_submit_url = "http://localhost:5000/vote_submit"
trusted_authority_get_token_url = "http://localhost:5000/get_token"
